### ISSUE TITLE
Api key

### ISSUE THREAD

**Issue by pcg92** [Mohammed-Benotmane/Jet-Hotels#1]
Hi, how can I try this app? I need an api key
{"message":"Invalid API key. Go to https:\/\/docs.rapidapi.com\/docs\/keys for more info."}

Any idea? Thanks

**Comment by Mohammed-Benotmane** [comment]
Hi, the website that provide the API change their link.
you can get an API key from this link:
[API KEY](https://rapidapi.com/apidojo/api/travel-advisor/)
